rest:
  - authentication: basic
    resource: https://ws.dvienergi.com/API/
    method: POST
    scan_interval: 5
    payload: '{"usermail": "YOUR_MAIL",	"userpassword": "YOUR_PSWD",	"fabnr":YOUR_FAB_NO,	"get":{"bestgreen":0,"sensor":1,"relay":1,"timer":0,"userSettings":1}}'
    sensor:
      - name: "Dvi Heatpump Sensors"
        json_attributes_path: $.output.sensor
        value_template: "OK"
        json_attributes:
          - Sensor.Date
          - Centralheating.Forward
          - Centralheating.Return
          - Storagetank.Hotwater
          - Roomtemperature
          - Storagetank.Centralheating
          - LV.Evaporator1
          - Outsidetemperature
          - Energycatcher
          - Solarheating
          - LV.Evaporator2
          - Highpressure
          - Lowpressure
          - Brine.Return
          - Brine.Forward
          - Heatmeter.Flow
          - Heatmeter.kW
          - Heatmeter.Forward
          - Heatmeter.Return
          - Powermeter.kW
          - Powermeter.kWh
      - name: "Dvi Heatpump Settings"
        json_attributes_path: $.output.userSettings
        value_template: "OK"
        json_attributes:
          - Centralheat.State
          - Centralheat.Curve
          - Centralheat.CurveTemp
          - Centralheat.Temp
          - Hotwater.State
          - Hotwater.Temp
          - Hotwater.Clock
      - name: "Dvi Heatpump Relays"
        json_attributes_path: $.output.relay
        value_template: "OK"
        json_attributes:
          - Relay1
          - Relay2
          - Relay3
          - Relay4
          - Relay5
          - Relay6
          - Relay7
          - Relay8
          - Relay9
          - Relay10
          - Relay11
          - Relay12
          - Relay13
          - Relay14